[project]
name = "script"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi>=2025.8.3",
    "dashscope>=1.24.1",
    "dotenv>=0.9.9",
    "filecaching>=0.0.3",
    "requests>=2.32.4",
    "GitPython>=3.1.0",
]
